version: "3.8"

services:
  db:
    image: "postgres:12.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    build: .
    command: bash start.sh
    ports:
      - "3000:3000"
    environment:
      - DB_PASSWORD=postgres
    volumes:
      - .:/rails-googleforms-api
      - gems:/gems
    depends_on:
      - db

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - "1025:25"
      - "1080:80"

volumes:
  postgres:
  gems:
